apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: {{ include "helm.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
  {{ range .Values.app.hosts }}
  - host: {{ $.Values.app.context }}{{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            port:
              name: http
            name: {{ include "helm.fullname" $ }}
    {{ end }}
  tls:
  - hosts:
    {{ range .Values.app.hosts }}
    - {{ . }}
    {{ end }}
    secretName: {{ .Values.app.certificate.secret }}
