apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "helm.fullname" . }}
  name: {{ include "helm.fullname" . }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: {{ include "helm.fullname" . }}
  type: ClusterIP
