name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3

    - name: Build docker image
      shell: bash
      env:
        TLS_SECRET: ${{ secrets.TLS_SECRET }}
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        TAG="$(git rev-parse --short HEAD)"
        docker build \
          --build-arg INSTALL=ci \
          --tag ghcr.io/flo-adikwu/portfolio:$TAG \
          .
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/flo-adikwu/portfolio:$TAG

        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        echo "$KUBE_CONFIG" | base64 --decode >> .kubeconfig.yaml

        helm upgrade --install \
          portfolio .deployment/helm \
          --set app.image.tag=$TAG \
          --set app.certificate.secret=$(echo -n "$TLS_SECRET" | base64 --decode) \
          --kubeconfig ./.kubeconfig.yaml
