name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3

    - name: Build docker image
      shell: bash
      run: |
        docker build --tag portfolio:v0.0.0 .
        docker image ls
