name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3

    - name: Build docker image
      shell: bash
      run: |
        TAG="$(git rev-parse --short HEAD)"
        docker build \
          --build-arg INSTALL=ci \
          --tag ghcr.io/flo-adikwu/portfolio:$TAG \
          .
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/flo-adikwu/portfolio:$TAG
